services:
  asf:
    image: justarchi/archisteamfarm:latest
    container_name: asf
    restart: unless-stopped
    pull_policy: always
    volumes:
      - config:/app/config
    networks:
      - local

volumes:
  config:

networks:
  local:
    external: true
