services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vault
    restart: unless-stopped
    pull_policy: always
    volumes:
      - ./data:/data
    networks:
      - local
    environment:
      I_REALLY_WANT_VOLATILE_STORAGE: true
      SIGNUPS_ALLOWED: false

networks:
  local:
    external: true
