services:
  kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    pull_policy: always
    networks:
      - local

networks:
  local:
    external: true
