services:
  kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    pull_policy: always
    volumes:
      - data:/app/data
    networks:
      - local

volumes:
  data:

networks:
  local:
    external: true
